version: "3"

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: us-east4-docker.pkg.dev/pivotal-data-437717-t8/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
      args:
        - AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
        - AUTH_DIRECT_URL_DB=${AUTH_DIRECT_URL_DB}
    image: us-east4-docker.pkg.dev/pivotal-data-437717-t8/image-registry/auth-ms
    environment:
      - SECRET_JWT=${SECRET_JWT}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - DIRECT_URL=${AUTH_DIRECT_URL_DB}
      - NATS_SERVERS=nats://nats-server:4222


  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: us-east4-docker.pkg.dev/pivotal-data-437717-t8/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db


  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: us-east4-docker.pkg.dev/pivotal-data-437717-t8/image-registry/orders-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}
